### ISSUE TITLE
Car network construction using iGraph - most have inf from navigation

### ISSUE THREAD

**Issue by TheYuanLiao** [jorgegil/osm-pg-etl#3]
Hi,

I tested this line of code and calculated travel time and distance from a few locations to the rest of zones in Canada.
`G = ig.Graph.TupleList(network,directed=False, vertex_name_attr='nodeid',edge_attrs=['edgeid','cost'])`
Any particular reason to set directed as False? I tried True but it did not work. All the returned travel time and distance are inf.
With the above line of code, the travel time and distance have the below results which I think there is something wrong. Because the majority of places as origin/destination are not connected in the graph.

Routing from 1 to the rest: inf, time: 5725/9858, distance: 5725/9858
Routing from 2 to the rest: time: 9809/9858, distance: 9809/9858
Routing from 3 to the rest: time: 572/98585, distance: 5725/9858
Routing from 4 to the rest: time: 5725/9858, distance: 5725/9858

**Comment by jorgegil** [comment]
Directed = False simply because I'm not sure we have attributes for links with dual directions. If we set the graph as directed it will follow the direction of the links always, and increase distances where the representation does not have separate links for each lane (very common). In my previous work it was not important to have it directed, but we must investigate here.

Before running, we must test if the network is fully connected. The giant connected component is the one we keep, any small isolated clusters must be removed so that origins/destinations don't "snap" to an isolated link - unreachable.
But, if these smaller components are too many or too big, we might be missing links. We must do this connected component analysis, and add an attribute to the graph table with the id of the connected components, and map them to inspect.

**Comment by TheYuanLiao** [comment]
This captures the largest component: `G.components().giant()` For the case of Canada, the largest component has a share of nodes as 96%. By keeping the largest connected graph for routing, the issue is solved.
